# Generated by Django 3.2.21 on 2023-10-01 20:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0011_auto_20230928_1742'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to=settings.AUTH_USER_MODEL)),
                ('featured_image_url', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_image_url', to='products.product')),
                ('likes', models.ManyToManyField(blank=True, related_name='reviews_likes', to=settings.AUTH_USER_MODEL)),
                ('product_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_name', to='products.product')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
