# Generated by Django 3.2.21 on 2023-10-05 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='product_name',
            field=models.ForeignKey(limit_choices_to={'orderlineitem__isnull': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_name', to='products.product'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1),
        ),
    ]
