# Generated by Django 3.2.21 on 2023-10-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='id',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='likes',
        ),
        migrations.AddField(
            model_name='reviews',
            name='reviews_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
