# Generated by Django 3.2.21 on 2023-09-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20230916_1924'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex')], max_length=1, null=True),
        ),
    ]
