# Generated by Django 3.2.21 on 2023-09-28 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20230927_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.ForeignKey(blank=True, default='male', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.gender'),
        ),
    ]
