# Generated by Django 3.2.21 on 2023-09-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
